# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85c664c1baf32a6be88688f7fd98edd933741548e91e1796ac23f3ab11cc0772d77881e13a774f596583d3a73db9454f0acb561357796872ab8273f23499be35

test:
  secret_key_base: 1d0faddda8e771fc79b4e7d0de6a55f5513dc65bd4b40a97f1765a250414ee0289c8fac0384a8d39e452aa5d25bda511a31041124c6dc66db5af69c35fd25999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
